const mongoose = require('mongoose');

const tripSchema = new mongoose.Schema({
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    title: {
        type: String, // e.g., "Paris Bike Trip"
        required: true
    },
    country: String,
    city: String,
    type: {
        type: String,
        enum: ['trek', 'bike'],
        required: true
    },
    duration: Number, // in days
    routeData: {
        type: Object, // GeoJSON or custom route object from LLM
        required: true
    },
    totalDistanceKm: Number,
    imageUrl: String,
    weatherForecast: Object, // Verification snapshot
    itinerary: [Object],     // Day-by-day description text generated by LLM
    createdAt: {
        type: Date,
        default: Date.now
    }
});

module.exports = mongoose.model('Trip', tripSchema);
